### ISSUE TITLE
Any chance of a swiftUI version of this? I've found information of EventKit & EventKitui rarer than unicorn S*!t

### ISSUE THREAD

**Issue by my4paws** [nemecek-filip/EKEventKit.Example#1]

**Comment by nemecek-filip** [comment]
Maybe? But so far I don't have much SwiftUI experience.. Is there something specific you need to achieve with EventKit?

**Comment by my4paws** [comment]
Thank you for replying. Because I've only been learning to code for a few months I've done so exclusively in SwiftUI and am totally lost looking at UIKit stuff. While learning I'm applying what I can to an app project idea that can help with my day job. A part of that will be to register bookings to iOS calendar with event kit. 
So to start with at least I'm hoping to replicate the same functionality as your demo here ( but in SwiftUI ) If I managed that much I think I could probably adapt it to do more app specific stuff afterwards. So yeah... a SwiftUI version of this would be exactly what I need to get up and running with Eventkit. 
I guess I won't know what gaps in knowledge I might still be missing until I hit the next roadblock :)

**Comment by nemecek-filip** [comment]
Got it! I see what I can do :-)

**Comment by nemecek-filip** [comment]
I have started working on SwiftUI version so I am closing this issue.. :)
