### ISSUE TITLE
Suggestion to break list into day segments

### ISSUE THREAD

**Issue by my4paws** [nemecek-filip/EKEventKit.Example#3]
To make reading the time line easier

**Comment by nemecek-filip** [comment]
You mean to have headers with dates to separate the events?

**Comment by my4paws** [comment]
Yes... exactly that :)

**Comment by nemecek-filip** [comment]
I see, I may try this in the future but I would like to focus mostly on EventKit itself not various options for presenting the stuff because there are so many :)

**Comment by my4paws** [comment]
Right, I totally understand it's beyond the scope of the demo. Thanks anyway.

**Comment by nemecek-filip** [comment]
Or you can fork this repo and try the headers. I will be happy to help, however I am not sure how would I approach this. Probably first separate loaded events by days into some kind of [Date: [EKEVent]] dictionary and use that for List with grouping maybe

**Comment by my4paws** [comment]
Thanks for everything.

I've implemented your code in my project and its working the same as the demo, except I changed the interval to a single day and am passing a selected date to the "loadEvents" function from a datePicker. As below:

Code*
let startOfDay = Calendar.current.startOfDay(for: self.selectedDate.selectedDate)
let endOfDay = Calendar.current.startOfDay(for: self.selectedDate.selectedDate.advanced(by: TimeInterval.day))
**
I'm trying to return a view that shows the .selectedDate

However the list is not updating to the "selectedDate" and always shows the events for current date. 
Do you have an idea how I can force the list to update to .selectedDate whenever a new date is chosen by the picker? 
thanks

**Comment by nemecek-filip** [comment]
How is your selectedDate implemented? I think it should be @State or @ObservableObject so SwiftUI can detect changes and rerender the views.

**Comment by my4paws** [comment]
In the view that contains both the datePicker & the foreach list showing the retrieved events.

Properties:

`@State var selectedDate = datepicker()`

body:
```

DatePicker(
                        selection: $selectedDate.selectedDate,
                        in: dateClosedRange,
                        displayedComponents: [.date, .hourAndMinute], label: { Text("Is hidden label") })
                    
                }
                List {
                    if eventsRepository.events?.isEmpty ?? true {
                        Text("No Walkies today")
                            .font(.headline)
                            .foregroundColor(.secondary)
                    }
                    ForEach(eventsRepository.events ?? []) { event in
                        EventRow(event: event).onTapGesture(count: 2) {
                            self.showEditFor(event)
                            self.haptics.notificationOccurred(.error)
                        }

```
Then I created a class that conforms to ObservableObject

class code:

```
class datepicker: ObservableObject{
    var selectedDate: Date = Date() // I'm thinking the problem lies here
}
```

EventsRepository.swift:

```
@ObservedObject var selectedDate = datepicker()


    func loadEvents(completion: @escaping (([EKEvent]?) -> Void)) {
        requestAccess(onGranted: {
            //let dayFromNow = Date().advanced(by: TimeInterval.day)
            let startOfDay = Calendar.current.startOfDay(for: self.selectedDate.selectedDate)
            let endOfDay = Calendar.current.startOfDay(for: self.selectedDate.selectedDate.advanced(by: TimeInterval.day))
             let predicate = self.eventStore.predicateForEvents(withStart: startOfDay, end: endOfDay, calendars: Array(self.selectedCalendars ?? []))

             let events = self.eventStore.events(matching: predicate)

             completion(events)
        }) {
            completion(nil)
        }
    }

```
I have really struggled with grasping the methods used to pass data from one view to another, and unfortunately have no-one at all here to ask when I get stuck or need explanations of why and how things work. Theres a LOT of trail and error involved in my coding, which is mostly error until I literally stumble upon something that works :)

**Comment by nemecek-filip** [comment]
I would try adding `@Published` to the `selectedDate` in datepicker class and also changing `@State var selectedDate = datepicker() ` to `@ObservedObject var selectedDate = datepicker()`. Also you try asking here - https://www.hackingwithswift.com/forums/swiftui I think it has better chance that someone will know how to fix it. I am SwiftUI beginner myself and it is possible that my example code is not best structured :)
