### ISSUE TITLE
Recurring events issue

### ISSUE THREAD

**Issue by my4paws** [nemecek-filip/EKEventKit.Example#5]
If an event is set up as recurring,  the StartDate for each returned event is always shown as the first date only.

eg: a returned event list might look like.
In 3 days ( returns 29th Sept in list & is correct 29th Sept)
In 4 days ( returns 30th Sept in list & is correct 30th Sept)
In 3 days ( returns 29th Sept in list but is actually 6th Oct)
In 4 days ( returns 30th Sept in list but is actually 7th Oct)
etc...

This seems like a bug in eventKit but maybe you have an idea?

**Comment by nemecek-filip** [comment]
Hi, this happens using my example or in your app? I haven't tried recurring events much but I guess it isn't EventKit bug since this frameworks has been there for years and I believe such serious issue would have been fixed by now :)

**Comment by my4paws** [comment]
Hi

It will happen in both my app ( which is adapted from your example ) AND with your clean Swiftui example downloaded directly from GitHub and run on the simulator (IOS 14). 

PS: the recurring event doesn't have to have been created from your code. So has nothing to do with the way the event was created. A recurring event made with IOS calendar app will produce the same result.

**Comment by my4paws** [comment]
just wanted to add because I think it provides hope that the issue is fixable. This problem with recurring events is confined to your SwiftUI example. There's no such problem with the UIKit example you provide.
I hope you are able to pin it down. ;)

**Comment by nemecek-filip** [comment]
Thanks for the info. I briefly checked UIKit version yesterday but did not find the issue you described. Interesting that it only happens with SwiftUI version.

**Comment by my4paws** [comment]
From what I've been able to find, it looks like you're being returned the .occuranceDate instead of the .startDate for a recurring event. But nowhere in your code do you ask for that. (that I could see).
Also if it helps, the issue is confined to future events only. In my own app I also retrieve past events & the same recurring events are reported correctly with .startDate once they are "before" current Date()
I just pray there's a solution for SwiftUI / eventKit version as my personal app needs this to work :)

**Comment by nemecek-filip** [comment]
I checked the relevant code and it seems to same to me. The `occurrenceDate`  should be the date of the first event in the series, see - https://developer.apple.com/documentation/eventkit/ekevent/1507244-occurrencedate

**Comment by my4paws** [comment]
Oh no that's tragic 😭...  do you now believe this to be a bug in IOS/ Eventkit rather than an issue with your example code? Will you be able to report it to Apple maybe?

**Comment by nemecek-filip** [comment]
I did another check and this time created daily repeat event and checked it in both project. You are right, SwiftUI shows exactly the same relative time for all events. I am pretty sure this is some dumb mistake that I made.

**Comment by nemecek-filip** [comment]
Okay, it is fixed. The issue was in the `EKEvent` extension to make it conform to `Identifiable`. I removed it, added manual `id` to `ForEach` and not it works exactly as UIKit version. @my4paws

**Comment by my4paws** [comment]
Confirmed it's fixed. 
Awesome work. Thank you so much!

**Comment by nemecek-filip** [comment]
Great`
