### ISSUE TITLE
EKEventEditViewController initial focus

### ISSUE THREAD

**Issue by my4paws** [nemecek-filip/EKEventKit.Example#6]
Hi

Do you know if there is a way to change the initial focus of the view controller from the title field to the start date selection instead? 
I'm providing the title & event duration automatically already, so choosing the startDate & time is often the only edit required. Would be great to remove an unnecessary step in my app by having the initial focus ready to go. Thank you so much again for providing this example.

**Comment by nemecek-filip** [comment]
Hello, I don't think this is possible. Maybe in your case creating your own custom view to handle this input would be better? This way users can change only the stuff you allow. Maybe this will help :-) https://nemecek.be/blog/28/how-to-save-event-into-users-calendar

**Comment by nemecek-filip** [comment]
Closing this issue, feel free to open new one if you need additional help.
